services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: kxback
    runtime: ruby
    plan: free # optional; defaults to starter
    startCommand: "./bin/render-build.sh"
    numInstances: 1
    envVars:
      - key: BUNDLER_VERSION
        value: 2.4.20 
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_MASTER_KEY
        sync: false
      - key: LANG
        value: en_US.UTF-8
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: PORT
        sync: false

databases: # Render PostgreSQL database
  - name: postgres-db
    plan: free

