services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: kxback
    dockerfilePath: ./Dockerfile
    dockerCommand: ./entrypoints/docker-entrypoint.sh
    runtime: docker
    plan: starter # optional; defaults to starter
    numInstances: 1
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: LANG
        value: en_US.UTF-8
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled

databases: # Render PostgreSQL database
  - name: postgres-db
    plan: free

