services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: kxback
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/rails server"
    plan: free # optional; defaults to starter
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: LANG
        value: en_US.UTF-8
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled

databases: # Render PostgreSQL database
  - name: postgres-db
    plan: free

    # ipAllowList: [] # only allow internal connections
